### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mtfs14** [udf/factorio-auto-resource-redux#5]
i got two bug with v0.0.5 + SE mod and their dependencies, first when i tried to change a value of fuel and second when i drop item to auto resource storage chest. here's the error code i received.

The mod Auto Resource Redux (0.0.5) caused a non-recoverable error.
Please report this error to the mod author.

this is the first bug
The mod Auto Resource Redux (0.0.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event auto-resource-redux::on_gui_click (ID 1)
LuaGuiElement doesn't contain key toggled.
stack traceback:
	[C]: in function '__newindex'
	__auto-resource-redux__/src/GUIComponentItemPrioritySet.lua:81: in function 'update_buttons'
	__auto-resource-redux__/src/GUIComponentItemPrioritySet.lua:114: in function 'update_components'
	__auto-resource-redux__/src/GUIComponentItemPrioritySet.lua:249: in function 'handler'
	__auto-resource-redux__/src/GUIDispatcher.lua:49: in function <__auto-resource-redux__/src/GUIDispatcher.lua:36>

and this is the second
Error while running event auto-resource-redux::on_nth_tick(1)
LuaGuiElement doesn't contain key toggled.
stack traceback:
	[C]: in function '__newindex'
	__auto-resource-redux__/src/GUIResourceList.lua:130: in function 'update_gui'
	__auto-resource-redux__/src/GUIResourceList.lua:158: in function 'on_tick'
	__auto-resource-redux__/control.lua:47: in function <__auto-resource-redux__/control.lua:38>

**Comment by udf** [comment]
What version of the game are you running?

**Comment by mtfs14** [comment]
i'm using pirated version 1.1.80 from fitgirl, thats why i posted the issues here, not the official mod website

**Comment by udf** [comment]
Older versions are not supported. Buy the game.

(1.1.80 released almost a year ago, why would a mod developed recently support it?)
