### ISSUE TITLE
Non-recoverable error

### ISSUE THREAD

**Issue by soran741** [udf/factorio-auto-resource-redux#6]
The mod Auto Resource Redux (0.0.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event auto-resource-redux::on_nth_tick(1)
LuaGuiElement doesn't contain key toggled.
stack traceback:
	[C]: in function '__newindex'
	__auto-resource-redux__/src/GUIResourceList.lua:130: in function 'update_gui'
	__auto-resource-redux__/src/GUIResourceList.lua:158: in function 'on_tick'
	__auto-resource-redux__/control.lua:47: in function <__auto-resource-redux__/control.lua:38>

**Comment by udf** [comment]
Please make a post on the mod portal page.
